"""A provider that answers without a network, deterministically.

This is what the whole test suite runs against, and what `AI_PROVIDER=mock` gives a
developer with no key. `docs/ai-system.md` asks for the entire feature to be built and
wired against this before a real vendor appears — so that when one arrives, everything
except the HTTP call is already known to work.

Deterministic matters for more than repeatability: the cache is keyed on provider and
model, and a mock that answered differently each time would make a cache hit and a cache
miss indistinguishable in a test.
"""

import asyncio

from pydantic import BaseModel, ConfigDict

from app.domain.interpretation import Interpretation, Language, VisualDescription
from app.domain.prompts import build_prompt, build_visual_prompt
from app.providers.ai.base import (
    AiError,
    InterpretationRequest,
    InterpretationResult,
    TokenUsage,
    VisualDescriptionResult,
)

MOCK_NAME = "mock"
MOCK_MODEL = "mock-1"


class _Template(BaseModel):
    """One language's fixed answer. A model rather than a dict so the shape is checked."""

    model_config = ConfigDict(frozen=True)

    visual: str
    interpretation: str
    themes: list[str]
    look_closer: str
    # The accessibility description, which the mock implements too — the whole point of
    # this provider is that a feature can be wired end to end before a real vendor exists,
    # and that applies to `VisualDescriptionProvider` exactly as it did to the first one.
    access_summary: str
    access_description: str


# Phrasing per language, so the mock exercises the same path a real provider does rather
# than returning English under a `pl` label — which `parse_interpretation` would reject.
_TEMPLATES: dict[Language, _Template] = {
    "en": _Template(
        visual="A generated description of {title}, standing in for a real one.",
        interpretation="This appears to be placeholder text. It may suggest that no AI "
        "provider is configured, and it is not a claim about the work.",
        themes=["placeholder", "mock provider", "no network"],
        look_closer="Nothing here was generated by a model; this text is fixed.",
        access_summary="A placeholder description of {title}.",
        access_description="This stands in for a spoken description of {title}. No AI "
        "provider is configured, so nothing here was written from the museum's own "
        "words. With a key in place, this is where the description would be.",
    ),
    "pl": _Template(
        visual="Wygenerowany opis dzieła {title}, w zastępstwie prawdziwego.",
        interpretation="To wygląda na tekst zastępczy. Może oznaczać, że nie skonfigurowano "
        "żadnego dostawcy AI, i nie jest to twierdzenie o dziele.",
        themes=["tekst zastępczy", "dostawca testowy", "bez sieci"],
        look_closer="Nic tutaj nie powstało w modelu; ten tekst jest stały.",
        access_summary="Zastępczy opis dzieła {title}.",
        access_description="To miejsce na opis dzieła {title} czytany na głos. Nie ma "
        "skonfigurowanego dostawcy AI, więc nie powstał tu żaden tekst na podstawie "
        "opisu muzeum. Po dodaniu klucza pojawi się tutaj prawdziwy opis.",
    ),
}


class MockProvider:
    """Implements `InterpretationProvider` without leaving the process."""

    def __init__(
        self,
        *,
        name: str = MOCK_NAME,
        model: str = MOCK_MODEL,
        fail_with: AiError | None = None,
        latency_seconds: float = 0.0,
    ) -> None:
        self.name = name
        self.model = model
        # Failure and slowness are configurable because every failure path in
        # docs/product-spec.md needs a test, and a provider that cannot be made to fail
        # cannot exercise the circuit breaker or the request timeout.
        self._fail_with = fail_with
        self._latency_seconds = latency_seconds
        self.calls = 0
        """How many times a caller got past the cache. Tests assert on this to prove the
        cache is doing something, which is otherwise invisible."""

    async def interpret(self, request: InterpretationRequest) -> InterpretationResult:
        self.calls += 1
        if self._latency_seconds:
            await asyncio.sleep(self._latency_seconds)
        if self._fail_with is not None:
            raise self._fail_with

        template = _TEMPLATES[request.language]
        title = request.artwork.title or "an untitled work"
        interpretation = Interpretation(
            visual_description=template.visual.format(title=title),
            interpretation=template.interpretation,
            themes=list(template.themes),
            look_closer=template.look_closer,
            language=request.language,
        )
        # Not a real count. Length of the prompt in words is enough to make budget
        # arithmetic observable in tests without pretending to be a tokenizer.
        prompt = build_prompt(request.artwork, request.language)
        return InterpretationResult(
            interpretation=interpretation,
            usage=TokenUsage(
                input_tokens=len(f"{prompt.system} {prompt.content}".split()),
                output_tokens=len(template.interpretation.split()),
            ),
        )

    async def describe(self, request: InterpretationRequest) -> VisualDescriptionResult:
        """`VisualDescriptionProvider`, so the accessibility path can be wired and tested
        with no key and no network — the same reason this class exists at all."""
        self.calls += 1
        if self._latency_seconds:
            await asyncio.sleep(self._latency_seconds)
        if self._fail_with is not None:
            raise self._fail_with

        template = _TEMPLATES[request.language]
        title = request.artwork.title or "an untitled work"
        prompt = build_visual_prompt(request.artwork, request.language)
        return VisualDescriptionResult(
            description=VisualDescription(
                summary=template.access_summary.format(title=title),
                description=template.access_description.format(title=title),
                language=request.language,
            ),
            usage=TokenUsage(
                input_tokens=len(f"{prompt.system} {prompt.content}".split()),
                output_tokens=len(template.access_description.split()),
            ),
        )
