#!/usr/bin/env python
"""Record the bundled fallback set of artworks.

Run occasionally, committed output. These records are what a fresh clone shows when there
is no index yet and the AIC API cannot be reached, so they are captured from real
responses rather than written by hand — the same rule the test fixtures follow.

    uv run python scripts/build_fallback_set.py --count 30

Only the metadata is bundled. The images still come from AIC at display time; committing
them would make this repository a partial mirror of the collection.
"""

import argparse
import asyncio
import json
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.core.config import get_settings
from app.domain.indexing import is_indexable
from app.providers.aic.client import MAX_LIMIT, AicClient
from app.services.fallback import DEFAULT_FALLBACK_PATH

logger = logging.getLogger("build_fallback_set")


async def build(count: int, destination: Path) -> int:
    settings = get_settings()
    chosen: dict[int, dict[str, object]] = {}
    iiif_base: str | None = None

    async with AicClient(settings) as client:
        page = 1
        # `is_boosted` is AIC's own essentials selection, so a boosted work is a better
        # first impression than a random one. Fall back to any eligible work if the
        # boosted ones run out before we have enough.
        while len(chosen) < count and page <= 5:
            result = await client.search_public_domain(limit=MAX_LIMIT, page=page)
            iiif_base = result.iiif_base
            eligible = [a for a in result.artworks if is_indexable(a)]
            for artwork in sorted(eligible, key=lambda a: not a.is_boosted):
                if len(chosen) >= count:
                    break
                chosen[artwork.id] = artwork.model_dump(mode="json", exclude_none=True)
            page += 1

    if not chosen or iiif_base is None:
        raise SystemExit("AIC returned nothing usable; fallback set not written")

    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "_comment": (
            "Generated by scripts/build_fallback_set.py from live AIC responses. "
            "Shown only when there is no local index and the API is unreachable."
        ),
        "iiif_base": iiif_base,
        "artworks": list(chosen.values()),
    }
    destination.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    logger.info("Wrote %d artworks to %s", len(chosen), destination)
    return len(chosen)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=30)
    parser.add_argument("--out", type=Path, default=DEFAULT_FALLBACK_PATH)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)-8s %(message)s")
    asyncio.run(build(args.count, args.out))


if __name__ == "__main__":
    main()
